float:
  euclidean:
    - base_args: ['@metric']
      constructor: Vecdb
      disabled: false
      docker_tag: ann-benchmarks-vecdb
      module: ann_benchmarks.algorithms.vecdb
      name: vecdb
      run_groups:
        M-12:
          arg_groups: [{M: 12, efConstruction: 200}]
          args: {}
          query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
        M-16:
          arg_groups: [{M: 16, efConstruction: 200}]
          args: {}
          query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
        M-24:
          arg_groups: [{M: 24, efConstruction: 300}]
          args: {}
          query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
  angular:
    - base_args: ['@metric']
      constructor: Vecdb
      disabled: false
      docker_tag: ann-benchmarks-vecdb
      module: ann_benchmarks.algorithms.vecdb
      name: vecdb
      run_groups:
        M-16:
          arg_groups: [{M: 16, efConstruction: 200}]
          args: {}
          query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
        M-24:
          arg_groups: [{M: 24, efConstruction: 300}]
          args: {}
          query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
